
export type ProjectMode = 'PREDATOR' | 'CHRISTIAN' | 'HOROSCOPE' | 'VITALITY';
export type VideoFormat = 'VERTICAL' | 'HORIZONTAL';
export type Language = 'RUSSIAN' | 'ENGLISH';

export interface Battle {
  round: number;
  animal_a: string;
  animal_b: string;
  winner: string;
  description: string;
}

export interface Scenario {
  title: string;
  meta_description: string;
  video_generation_prompt: string;
  battles: Battle[];
  metadata: {
    total_unique_animals: number;
    legendary_battle_round: number;
  };
}

// --- SHARED CHAPTER TYPES ---
export interface ChapterItem {
  title: string;          // e.g. "Aries" or "Step 1"
  content_visual: string; // Subtitle text
  content_spoken: string; // Voiceover text
}

export interface ContentChapter {
  chapter_title: string;  // e.g. "Sphere of Love" or "The Diet Protocol"
  chapter_intro: string;  // Spoken intro for this chapter
  items: ChapterItem[];   // List of items (Signs, Steps, Prayers)
}

// --- DOMAIN TYPES ---

export interface ScriptureContent {
  format?: VideoFormat;
  title: string;
  meta_description: string;
  video_generation_prompt: string;
  tags?: string[];
  youtube_description?: string;
  
  // Shorts (Legacy)
  verse?: string;
  reference?: string;
  reflection?: string;
  visual_prompt: string;

  // Long Form
  chapters?: ContentChapter[];
  
  // Marathon Architecture
  marathon_outline?: string[]; // List of 20 titles generated by the Architect
}

export interface HoroscopeContent {
  format: VideoFormat;
  title: string;
  meta_description: string;
  video_generation_prompt: string;
  trend_source: string;
  visual_theme: string;
  tags?: string[];
  youtube_description?: string;
  
  // Shorts
  intro_visual?: string; 
  intro_spoken?: string; 
  signs?: { sign: string; prediction_visual: string; prediction_spoken: string; }[];
  outro_visual?: string;
  outro_spoken?: string;

  // Long Form
  chapters?: ContentChapter[];
}

export interface VitalityContent {
  format?: VideoFormat;
  title: string;
  meta_description: string;
  video_generation_prompt: string;
  topic: string;
  thumbnail_prompt: string; 
  tags?: string[];
  youtube_description?: string;
  
  // Shorts
  scenes?: { id: number; micro_script: string; voiceover: string; overlay_text: string; image_prompt: string; }[];

  // Long Form
  chapters?: ContentChapter[];
}

export interface GeneratedImage {
  id: string; 
  url: string; 
  status: 'pending' | 'loading' | 'completed' | 'error';
  prompt: string;
}

export interface Track {
  id: string;
  name: string;
  artist_name: string;
  audio: string; 
  duration: number;
  image: string;
}

export enum AppStep {
  SCENARIO = 1,
  IMAGERY = 2,
  AUDIO = 3,
  ASSEMBLY = 4,
  RESULT = 5
}
